### PR TITLE
Add Current Track Display

### PR DESCRIPTION
**Pull request by faxblaster**
Shows Current Track on modules.index and modules.show pages. 

**Screenshots:** 
Screen Shot 2020-09-16 at 11 03 49 AM

Screen Shot 2020-09-16 at 11 03 38 AM

Screen Shot 2020-09-16 at 11 03 25 AM

Screen Shot 2020-09-16 at 11 03 19 AM

### CODE REVIEW

**Comment by faxblaster** [comment]
Updated the layout after a design discussion. 

**Screenshots:**
Screen Shot 2020-09-17 at 3 34 48 PM

Screen Shot 2020-09-17 at 3 34 23 PM

**Comment by mattstauffer** [comment]
I like it as a start, but:

1. I don't need it to be close-able
2. Can "change settings" be a little less bold
3. The alert makes it really draw my attention, which I don't want; it needs to be informational but not attention-grabbing.

I know this isn't what I said at first, but what if we _only_ show it on the Modules page, and we integrate it into the modules header somewhere?

**Comment by faxblaster** [comment]
Oooh yeah! Maybe something like this? 

Screen Shot 2020-09-17 at 4 20 24 PM

**Comment by mattstauffer** [comment]
Looks great!

**Pull request merged**
